source 'https://rubygems.org'

gem 'bundler'
gem 'asciidoctor'
gem 'asciidoctor-pdf'
gem 'asciidoctor-revealjs'
gem 'coderay'
gem 'rouge'
gem 'pygments.rb'
gem 'filewatcher'
gem 'asciidoctor-diagram'
gem 'prawn'
gem 'asciidoctor-plantuml'